---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-1204
    run_list: apt::default

suites:
  - name: default
    run_list:
      - recipe[chef-php-ppa::default]
    attributes:
