---
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:

- name: ubuntu-1204
  driver_plugin: ec2
  driver_config:
    image_id: ami-59a4a230
    username: <%= ENV['AWS_USERNAME'] %>
    ssh_key: /home/travis/<%= ENV['EC2_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[chef-php-ppa::default]
    attributes:
